import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";

import Footer from "./components/Footer";

import Navbar from "./components/Nav/Navbar";
import { Suspense } from "react";
import NavbarSkeleton from "./components/Nav/NavbarSkeleton";


const hindSiliguri = Hind_Siliguri({
  
  subsets: ['bengali', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      data-theme="light"
      className={`${hindSiliguri.className} h-full antialiased`}
    >
      <body className="min-h-full   bg-[#F0FFF0]/50 " >
      <Suspense  fallback={<NavbarSkeleton />}>

        <Navbar></Navbar>
      </Suspense>
        <main className="">

      {children}
        </main>
       

        <Footer></Footer>
     
      </body>
    </html>
  );
}
