import type { Metadata } from "next";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const hindSiliguri = Hind_Siliguri({
  
  subsets: ['bengali', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="bn"
      className={`${hindSiliguri.className} h-full antialiased`}
    >
      <body className="min-h-full  bg-[#F0FFF0]/50 " >
        <Navbar></Navbar>
        <main className="">

      {children}
        </main>
        <div className="max-w-7xl mx-auto">

        <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
